client_config_backend: settings
client_config:
  client_id: 687797358691-7j0kkr3c1i1ge276qp6ghpi9dheinvu9.apps.googleusercontent.com
  client_secret: qmpzK9B7CL80o_pxFPs_u6sB

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install